Content:
    blackbear_assessment:
        root_dir: ${ROOT_DIR}/assessment
    blackbear:
        root_dir: ${ROOT_DIR}/doc/content
    framework:
        root_dir: ${MOOSE_DIR}/framework/doc/content
    contact:
        root_dir: ${MOOSE_DIR}/modules/contact/doc/content
    heat_conduction:
        root_dir: ${MOOSE_DIR}/modules/heat_conduction/doc/content
    misc:
        root_dir: ${MOOSE_DIR}/modules/misc/doc/content
    tensor_mechanics:
        root_dir: ${MOOSE_DIR}/modules/tensor_mechanics/doc/content
    xfem:
        root_dir: ${MOOSE_DIR}/modules/xfem/doc/content
    stochastic_tools:
        root_dir: ${MOOSE_DIR}/modules/stochastic_tools/doc/content
    ray_tracing:
        root_dir: ${MOOSE_DIR}/modules/ray_tracing/doc/content
    optimization:
        root_dir: ${MOOSE_DIR}/modules/optimization/doc/content
    modules:
        root_dir: ${MOOSE_DIR}/modules/doc/content
        content:
            - help/finite_element_concepts/nodal_patch_recovery.md
            - application_usage/restart_recover.md
            - help/development/analyze_jacobian.md

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: BlackBear
        repo: https://github.com/idaholab/blackbear
        menu:
            Getting Started:
                Running BlackBear: getting_started/RunningBlackBear.md
                Input Structure: getting_started/BlackBearInputStructure.md
            Documentation:
                Systems: syntax/index.md
            Development:
                Software Quality: /sqa/index.md
                Code Coverage: https://mooseframework.inl.gov/blackbear/docs/coverage/
            Assessment: assessment/assessment_index.md

    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml

    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml

    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml

    MooseDocs.extensions.template:
        active: True

    MooseDocs.extensions.civet:
        test_results_cache: '/tmp/civet/jobs'
        remotes:
            blackbear:
                url: https://civet.inl.gov
                repo: idaholab/blackbear
            moose:
                url: https://civet.inl.gov
                repo: idaholab/moose
                location: ${MOOSE_DIR}

    MooseDocs.extensions.sqa:
        active: True
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
        repos:
            default: https://github.com/idaholab/blackbear
            moose: https://github.com/idaholab/moose
        categories:
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            tensor_mechanics: !include ${MOOSE_DIR}/modules/tensor_mechanics/doc/sqa_tensor_mechanics.yml
            stochastic_tools: !include ${MOOSE_DIR}/modules/stochastic_tools/doc/sqa_stochastic_tools.yml
            contact: !include ${MOOSE_DIR}/modules/contact/doc/sqa_contact.yml
            heat_conduction: !include ${MOOSE_DIR}/modules/heat_conduction/doc/sqa_heat_conduction.yml
            misc: !include ${MOOSE_DIR}/modules/misc/doc/sqa_misc.yml
            xfem: !include ${MOOSE_DIR}/modules/xfem/doc/sqa_xfem.yml
            ray_tracing: !include ${MOOSE_DIR}/modules/ray_tracing/doc/sqa_ray_tracing.yml
            optimization: !include ${MOOSE_DIR}/modules/optimization/doc/sqa_optimization.yml
            blackbear: !include ${ROOT_DIR}/doc/sqa_blackbear.yml
        requirement-groups:
            dgkernels: DGKernel Objects
            interfacekernels: InterfaceKernel Objects

    MooseDocs.extensions.bibtex:
        duplicates:
            - hales15homogenization

    MooseDocs.extensions.analytics:
        active: True
        google_measurement_id: G-NX6FRSG1H8

    MooseDocs.extensions.algorithm:
        active: True
